/*
 * FVenta.java
 *
 * Created on 12 de mayo de 2008, 10:55
 */

package interfaz;
import persistenciaBD.*;
import javax.swing.table.*;
import java.util.*;
/**
 *
 * @author  genar
 */
public class FVenta extends javax.swing.JInternalFrame {
    ModeloTablaLineas mtl = new ModeloTablaLineas();
    Venta ventaActual;
    /** Creates new form FVenta */
    public FVenta() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtArticulos = new javax.swing.JTable();
        tfCodVenta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfCodCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jlTotal = new javax.swing.JLabel();
        jbAceptar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfCodArticulo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfCant = new javax.swing.JTextField();
        tfDesc = new javax.swing.JTextField();
        jbAnadir = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jlNombre = new javax.swing.JLabel();

        setClosable(true);

        jLabel1.setText("Codigo Venta");

        jtArticulos.setModel(mtl);
        jtArticulos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jtArticulos);

        tfCodVenta.setEditable(false);

        jLabel2.setText("Codigo Cliente");

        tfCodCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCodClienteActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("DejaVu Sans", 1, 24));
        jLabel3.setText("Total:");

        jlTotal.setFont(new java.awt.Font("DejaVu Sans", 1, 24));
        jlTotal.setForeground(new java.awt.Color(39, 255, 0));
        jlTotal.setText("0,0");

        jbAceptar.setText("Aceptar venta");
        jbAceptar.setEnabled(false);
        jbAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAceptarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("DejaVu Sans", 1, 18));
        jLabel5.setText("€");

        jLabel6.setText("Codigo");

        tfCodArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCodArticuloActionPerformed(evt);
            }
        });

        jLabel7.setText("Descripcion");

        jLabel8.setText("Cantidad");

        tfCant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCantActionPerformed(evt);
            }
        });

        tfDesc.setEditable(false);

        jbAnadir.setText("Añadir");
        jbAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAnadirActionPerformed(evt);
            }
        });

        jButton3.setText("Borrar ultima linea");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 846, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(tfCodVenta))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tfCodCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jlNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jbAceptar)
                            .addGap(464, 464, 464)
                            .addComponent(jLabel3)
                            .addGap(53, 53, 53)
                            .addComponent(jlTotal)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel5)
                            .addContainerGap()))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCodArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCant, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfDesc, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbAnadir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfCodVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfCodCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCodArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(tfCant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(tfDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbAnadir)
                    .addComponent(jLabel6)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbAceptar)
                        .addGap(23, 23, 23))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlTotal)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAceptarActionPerformed
        procesarVenta();
        limpiarCampos();
}//GEN-LAST:event_jbAceptarActionPerformed

    public void limpiarCampos(){
        tfCodCliente.setText("");
        tfCodVenta.setText("");
        mtl = new ModeloTablaLineas();
        jtArticulos.setModel(mtl);
        
    }
    public void procesarVenta(){
        ventaActual = ControlVenta.obtenerInstancia().empezarVenta(tfCodCliente.getText());
        for(int i =0 ; i < mtl.getRowCount(); i++){
            LineaVenta lv = mtl.obtenerLinea(i);
            ControlVenta.obtenerInstancia().anadirLineaVenta(lv);
        }
        Venta v = ControlVenta.obtenerInstancia().terminarVenta(ventaActual);
        if(v!=null){
            new jdVentaFinalizada(v);
        }
    }
    
    private void tfCodClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCodClienteActionPerformed
        Cliente cli = ControlClientes.obtenerInstancia().obtenerCliente(tfCodCliente.getText());
        jlNombre.setText(cli.getNombre());
        String codBloq = ControlClientes.obtenerInstancia().obtenerCodBloqueo(cli);
        if(!codBloq.equals("0")){
            new DError("El cliente tiene un bloqueo de tipo: "+codBloq,"El cliente tiene un bloqueo y no puede realizar niguna compra hasta que no se solucione la situacion.\n El mensaje del bloqueo es: "+ControlClientes.obtenerInstancia().obtenerMensajeBloqueo(cli));
        }else{
            jbAceptar.setEnabled(true);
            tfCodVenta.setText(ControlVenta.obtenerInstancia().obtenerCodigoVentaLibre());
            tfCodArticulo.requestFocus();
        }
}//GEN-LAST:event_tfCodClienteActionPerformed

    private void tfCodArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCodArticuloActionPerformed
        Articulo art = ControlArticulos.obtenerInstancia().obtenerArticulo(tfCodArticulo.getText());
        tfDesc.setText(art.getDescripcion());
        tfCant.requestFocus();
    }//GEN-LAST:event_tfCodArticuloActionPerformed

    private void jbAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAnadirActionPerformed
        mtl.anadeLinea(ControlVenta.obtenerInstancia().crearLineaVenta(tfCodVenta.getText(),tfCodArticulo.getText(),tfCant.getText()));
        actualizarTotal();
        tfCodArticulo.setText("");
        tfCant.setText("");
        tfDesc.setText("");
}//GEN-LAST:event_jbAnadirActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        mtl.borraLinea(mtl.getRowCount()-1);
        actualizarTotal();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tfCantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCantActionPerformed
        jbAnadir.requestFocus();
    }//GEN-LAST:event_tfCantActionPerformed
    
    private void actualizarTotal(){
        jlTotal.setText(String.valueOf(mtl.obtenerTotal()));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAceptar;
    private javax.swing.JButton jbAnadir;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JLabel jlTotal;
    private javax.swing.JTable jtArticulos;
    private javax.swing.JTextField tfCant;
    private javax.swing.JTextField tfCodArticulo;
    private javax.swing.JTextField tfCodCliente;
    private javax.swing.JTextField tfCodVenta;
    private javax.swing.JTextField tfDesc;
    // End of variables declaration//GEN-END:variables
    
}
